#!/usr/bin/python3
"""Test BaseModel class"""

import unittest
from models.base_model import BaseModel

class TestBaseModel(unittest.TestCase):
    """Test BaseModel class"""

    def test_init(self):
        """Test initialization"""
        model = BaseModel()
        self.assertIsInstance(model, BaseModel)

    def test_str(self):
        """Test string representation"""
        model = BaseModel()
        self.assertIsInstance(str(model), str)

if __name__ == '__main__':
    unittest.main()